pipeline:
- name: Install composer dependencies
  type: command
  command: composer install --no-interaction --optimize-autoloader
  directory: $APP_ROOT
- name: Sync Drupal config
  type: command
  command: drush cim -y
  directory: $APP_ROOT